---
title: "Working with UserTests"
output: html_notebook
---

Start by properly preparing your data file, which should be saved in``.csv`` format. The data file should have either 3 or 4 columns, depending upon whether one or two test groups are being analyzed. 

In both cases, three of the columns should be: **Participant**, **Task**, and **Success**. The fourth (optional) column shuold be **Group**. See table 1:

Table 1

Participant | Task | Success | Group   
----------- | ---- | ------- | ----- 
 1          | 1    |  1      | CTCT    
 1          | 1    |  0      | MC      
 1          | 2    |  1      | CTCT    
 1          | 2    |  1      | MC      
 2          | 1    |  1      | CTCT    
 2          | 1    |  0      | MC      
 2          | 2    |  0      | CTCT    
 2          | 2    |  1      | MC      

Next, import the file into R.

```{r}
readr::
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

